### ISSUE TITLE
add ifconfig.me

### ISSUE THREAD

**Issue by rsharifnasab** [freedomofdevelopers/fod#469]
hi, 
thanks for your great project.
i recently noticed that `ifconfig.me` is no more accessible from Iran ip.
please consider adding this site to your great project too.

why this site is important? because we could check current ip address with this command 
`curl ifconfig.me`
[more info](https://www.tecmint.com/find-linux-server-public-ip-address/)

**Comment by aminvakil** [comment]
Adding it to proxy would defeat the purpose of ifconfig.me totallyOn Mar 27, 2021 03:16, Roozbeh Sharifnasab ***@***.***> wrote:
hi,
thanks for your great project.
i recently noticed that ifconfig.me is no more accessible from Iran ip.
please consider adding this site to your great project too.
why this site is important? because we could check current ip address with this command
curl ifconfig.me
more info

**Comment by rsharifnasab** [comment]
Oh! You are 100 percent right.
Thanks.
